include: "rules/common.smk"
include: "rules/variants.smk"
include: "rules/elements.smk"


rule all_variants:
    input:
        expand(
            "results/{id}/reporter_variants/{id}.reporter_variants.{method}.tsv.gz",
            method=config["method"],
            id=config["id"],
        ),
        expand(
            "results/{id}/reporter_genomic_variants/{id}.reporter_genomic_variants.{method}.bed.gz",
            method=config["method"],
            id=config["id"],
        ),


rule all_elements:
    input:
        expand(
            "results/{id}/reporter_elements/{id}.reporter_elements.{method}.tsv.gz",
            method=config["method"],
            id=config["id"],
        ),
        expand(
            "results/{id}/reporter_genomic_elements/{id}.reporter_genomic_elements.{method}.bed.gz",
            method=config["method"],
            id=config["id"],
        ),
