include: "rules/common.smk"
include: "rules/variants.smk"
include: "rules/elements.smk"


rule all_variants:
    input:
        expand(
            "results/{id}/reporter_variants/{id}.reporter_variants.{level}.tsv.gz",
            level=config["level"],
            id=config["id"],
        ),
        expand(
            "results/{id}/reporter_genomic_variants/{id}.reporter_genomic_variants.{level}.bed.gz",
            level=config["level"],
            id=config["id"],
        ),


rule all_elements:
    input:
        expand(
            "results/{id}/reporter_elements/{id}.reporter_elements.{level}.tsv.gz",
            level=config["level"],
            id=config["id"],
        ),
        expand(
            "results/{id}/reporter_genomic_elements/{id}.reporter_genomic_elements.{level}.bed.gz",
            level=config["level"],
            id=config["id"],
        ),
